#!/bin/sh
# Regenerate CHANGELOG.md from published GitHub release notes.
# Usage: scripts/gen-changelog.sh > CHANGELOG.md
# Requires: gh (authenticated), python3.
set -eu

REPO="${BACKSCROLL_REPO:-soren-achebe/backscroll}"

gh api "repos/$REPO/releases?per_page=100" --paginate | python3 -c '
import json, sys, re

releases = []
# --paginate concatenates JSON arrays; parse them all.
dec = json.JSONDecoder()
buf = sys.stdin.read()
i = 0
while i < len(buf):
    while i < len(buf) and buf[i] in " \r\n\t":
        i += 1
    if i >= len(buf):
        break
    arr, j = dec.raw_decode(buf, i)
    releases.extend(arr)
    i = j

releases = [r for r in releases if not r.get("draft") and not r.get("prerelease")]

def ver_key(tag):
    m = re.match(r"v?(\d+)\.(\d+)\.(\d+)", tag)
    return tuple(int(x) for x in m.groups()) if m else (0, 0, 0)

releases.sort(key=lambda r: ver_key(r["tag_name"]), reverse=True)

# Strip the per-release AI-disclosure footer (kept once at the top of this
# file instead). Variants: "*Built and maintained…*", "*backscroll is built
# and maintained…*", optionally preceded by a --- rule, possibly multi-line.
FOOTER = re.compile(
    r"(?:\n+-{3,})?\n+\*(?:backscroll is )?[Bb]uilt and maintained by an AI agent.*?$",
    re.S,
)

print("# Changelog")
print()
print("All notable changes to backscroll, newest first. Each entry is the")
print("curated release note published with that version; full diffs are on the")
print("[releases page](https://github.com/'"$REPO"'/releases).")
print()
print("backscroll is built and maintained by an AI agent (Soren Achebe).")
print()
print("<!-- Generated by scripts/gen-changelog.sh — do not edit by hand. -->")

for r in releases:
    tag = r["tag_name"]
    date = (r.get("published_at") or "")[:10]
    body = (r.get("body") or "").replace("\r\n", "\n").strip()
    body = FOOTER.sub("", body).strip()
    # Demote any headings in the body so release headers stay the hierarchy.
    body = re.sub(r"(?m)^(#{1,3}) ", r"#### ", body)
    print()
    print(f"## [{tag}](https://github.com/'"$REPO"'/releases/tag/{tag}) — {date}")
    print()
    print(body if body else "_No notes._")
'
